--------------------------------------------------------
--  File created - Friday-July-07-2023   
--------------------------------------------------------
DROP TABLE "SYSTEM"."TBLTWRARCHIVE" cascade constraints;
DROP TABLE "SYSTEM"."TBLTOWER" cascade constraints;
DROP TABLE "SYSTEM"."TBLTWRDATA" cascade constraints;
DROP TABLE "SYSTEM"."TBLTWRDATA" cascade constraints;
DROP TABLE "SYSTEM"."TBLTOWER" cascade constraints;
DROP TABLE "SYSTEM"."TBLTWRARCHIVE" cascade constraints;
--------------------------------------------------------
--  DDL for Table TBLTWRARCHIVE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTWRARCHIVE" 
   (	"DATADATE" DATE, 
	"SAPID" VARCHAR2(50 BYTE), 
	"PCU" NUMBER, 
	"IT" NUMBER, 
	"VT" NUMBER, 
	"TT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTOWER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTOWER" 
   (	"SAPID" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"DISTRICT" VARCHAR2(50 BYTE), 
	"BLOCK" VARCHAR2(50 BYTE), 
	"VILLAGE" VARCHAR2(50 BYTE), 
	"COMMISIION_DATE" DATE, 
	"CENSUS_CODE" NUMBER, 
	"PROJECT_ID" VARCHAR2(50 BYTE), 
	"APPENDIX_NO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTWRDATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTWRDATA" 
   (	"DATADATE" DATE, 
	"SAPID" VARCHAR2(50 BYTE), 
	"PCU" NUMBER, 
	"IT" NUMBER, 
	"VT" NUMBER, 
	"TT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTWRDATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTWRDATA" 
   (	"DATADATE" DATE, 
	"SAPID" VARCHAR2(50 BYTE), 
	"PCU" NUMBER, 
	"IT" NUMBER, 
	"VT" NUMBER, 
	"TT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTOWER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTOWER" 
   (	"SAPID" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"DISTRICT" VARCHAR2(50 BYTE), 
	"BLOCK" VARCHAR2(50 BYTE), 
	"VILLAGE" VARCHAR2(50 BYTE), 
	"COMMISIION_DATE" DATE, 
	"CENSUS_CODE" NUMBER, 
	"PROJECT_ID" VARCHAR2(50 BYTE), 
	"APPENDIX_NO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLTWRARCHIVE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBLTWRARCHIVE" 
   (	"DATADATE" DATE, 
	"SAPID" VARCHAR2(50 BYTE), 
	"PCU" NUMBER, 
	"IT" NUMBER, 
	"VT" NUMBER, 
	"TT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBLTWRARCHIVE
SET DEFINE OFF;
REM INSERTING into SYSTEM.TBLTOWER
SET DEFINE OFF;
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 1','Gujarat','Narmada','Dediapada','Village 1',to_date('09-SEP-21','DD-MON-RR'),150990,'Project 1',1);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 2','Gujarat','Narmada','Dediapada','Village 2',to_date('09-SEP-21','DD-MON-RR'),541156,'Project 1',2);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 3','Gujarat','Narmada','Dediapada','Village 3',to_date('09-SEP-21','DD-MON-RR'),712392,'Project 1',3);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 4','Gujarat','Narmada','Dediapada','Village 4',to_date('09-SEP-21','DD-MON-RR'),814397,'Project 1',4);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 5','Gujarat','Narmada','Dediapada','Village 5',to_date('09-SEP-21','DD-MON-RR'),194175,'Project 1',5);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 12','Gujarat','Kachchh','Nakhatrana','Village 12',to_date('14-SEP-21','DD-MON-RR'),202592,'Project 1',12);
Insert into SYSTEM.TBLTOWER (SAPID,STATE,DISTRICT,BLOCK,VILLAGE,COMMISIION_DATE,CENSUS_CODE,PROJECT_ID,APPENDIX_NO) values ('Tower 22','Maharashtra','Gondia','Deori','Village 22',to_date('22-SEP-21','DD-MON-RR'),101259,'Project 2',22);
REM INSERTING into SYSTEM.TBLTWRDATA
SET DEFINE OFF;
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 1',72,168,4074,22);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 2',42,160,2254,32);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 3',46,184,6497,63);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 4',21,163,2884,73);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 5',25,163,4712,26);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 12',20,101,5586,58);
Insert into SYSTEM.TBLTWRDATA (DATADATE,SAPID,PCU,IT,VT,TT) values (to_date('30-JUN-23','DD-MON-RR'),'Tower 22',29,138,4493,19);
--------------------------------------------------------
--  DDL for Index TBLTWRARCHIVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBLTWRARCHIVE_PK" ON "SYSTEM"."TBLTWRARCHIVE" ("DATADATE", "SAPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBLTOWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBLTOWER_PK" ON "SYSTEM"."TBLTOWER" ("SAPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TBLTWRDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."TBLTWRDATA_PK" ON "SYSTEM"."TBLTWRDATA" ("DATADATE", "SAPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBLTWRARCHIVE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("DATADATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("SAPID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("PCU" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("IT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("VT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" MODIFY ("TT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" ADD CONSTRAINT "TBLTWRARCHIVE_PK" PRIMARY KEY ("DATADATE", "SAPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLTOWER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("SAPID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("DISTRICT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("BLOCK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("VILLAGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("COMMISIION_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("CENSUS_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" MODIFY ("APPENDIX_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTOWER" ADD CONSTRAINT "TBLTOWER_PK" PRIMARY KEY ("SAPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBLTWRDATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("DATADATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("SAPID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("PCU" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("IT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("VT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" MODIFY ("TT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBLTWRDATA" ADD CONSTRAINT "TBLTWRDATA_PK" PRIMARY KEY ("DATADATE", "SAPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBLTWRARCHIVE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBLTWRARCHIVE" ADD CONSTRAINT "TBLTWRARCHIVE_FK1" FOREIGN KEY ("DATADATE", "SAPID")
	  REFERENCES "SYSTEM"."TBLTWRDATA" ("DATADATE", "SAPID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBLTWRDATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBLTWRDATA" ADD CONSTRAINT "TBLTWRDATA_FK1" FOREIGN KEY ("SAPID")
	  REFERENCES "SYSTEM"."TBLTOWER" ("SAPID") ON DELETE CASCADE ENABLE;
